# Generated by Django 5.2.17 on 2026-08-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=50)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('invoice_or_id', models.CharField(blank=True, max_length=50, null=True)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_type', models.CharField(max_length=50)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('fixed', 'Fixed'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('scope', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('kg_co2e_per_unit', models.FloatField()),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FuelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('delivery_date', models.DateField()),
                ('date_precision', models.CharField(choices=[('day', 'Day'), ('month', 'Month')], default='day', max_length=10)),
                ('fuel_type', models.CharField(max_length=20)),
                ('quantity_litres', models.FloatField()),
                ('cost_aud', models.FloatField(blank=True, null=True)),
                ('site_area', models.CharField(max_length=50)),
                ('is_credit_note', models.BooleanField(default=False)),
                ('exclude_from_emissions', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fuel Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=20)),
                ('incident_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('type_code', models.CharField(max_length=10)),
                ('severity', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('description', models.TextField()),
                ('ai_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_psychosocial_flag', models.BooleanField(blank=True, null=True)),
                ('ai_severity_consistent', models.BooleanField(blank=True, null=True)),
                ('ai_severity_inconsistency_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=10)),
                ('meter_description', models.CharField(max_length=100)),
                ('period', models.DateField()),
                ('consumption_kwh', models.FloatField()),
                ('unit_corrected', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('meter_id', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('fy_spend_aud', models.FloatField()),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='ingestion.supplier')),
            ],
        ),
    ]
